### ISSUE TITLE
Create a wisheslist

### ISSUE THREAD

**Issue by cookie0402** [CSCI-GA-2820-FA23-001/wishlists#2]
**As a** As a User
**I need** the ability to create a wishlist
**So that**  I can have a collection of products I aspire to purchase.
   
 ### Details and Assumptions
 * Create a RESTful API that processes requests: POST /wishlist. Request body contains
``` json
 {
    name: [wishlist_name]    
    owner: [user_id]
}
```
 * We will store product details in a MySQL/PostgreSQL database.
 * We will store items(products) in the wishlist in a MySQL/PostgreSQL database.
 * Each wishlist has: wishlist_id, customer_id, product_ids (List of products that the customer wishes to purchase)
 * We will store customer details in a MySQL/PostgreSQL database.

   
 ### Acceptance Criteria  
   
 ```gherkin
Given there are no customers in the database
When I create a customer
Then there should be 1 customer in the database.
```
 ```gherkin
Given there are no wishlists in the database
When I create a wishlist
Then there should be 1 wishlist in the database.
```

**Comment by chrisxhhh** [comment]
A few suggestions:
1. change the title to "Create a Wishlist"
2. delete bullet point 2 and 6, which belongs to #3 story
3. specify which route the create is using (/create maybe), and the REST method

**Comment by cookie0402** [comment]
got it! thanks
