### ISSUE TITLE
List Wishlists 

### ISSUE THREAD

**Issue by lingz0108** [CSCI-GA-2820-FA23-001/wishlists#5]
**As a** user
**I need** to list my wishlists
**So that** I can see and access the collections of the product I desire to purchase in the future
   
 ### Details and Assumptions
 * We will access the wishlists from our PostgreSQL database
 * Create a RESTful API that processes requests: GET /wishlist
 * When the request, GET /wishlist is received, returns all the matching results
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are no wishlist in the user’s account
 When the user request to list all wishlists or matching list
 Then the request succeeds and returns “0 wishlist found"
```

 ```gherkin
 Given there are wishlists in the user’s account
 When the user requests to list all wishlists
 Then the request succeeds and returns all the matching wishlists
```

**Comment by chrisxhhh** [comment]
I split it into two stories, see #9 story

**Comment by lingz0108** [comment]
Yeah I might have written too much in one story, thanks for splitting the unfiltered/filtered
