### ISSUE TITLE
List wishlists with a date filter

### ISSUE THREAD

**Issue by chrisxhhh** [CSCI-GA-2820-FA23-001/wishlists#9]
**As a** customer who has a lot of wishlists
**I need** to filter out my wishlists by date
**So that** I can narrow down the wishlist list displayed by time period
   
 ### Details and Assumptions
 * We will access the wishlists from our PostgreSQL database
 * Create a RESTful API that processes requests: GET /wishlist?{query} (for example, GET /wishlist?start=01-01-2018 &end=01-01-2023 )
 * When the request GET /wishlist?{query} is received, returns all the matching results
   
 ### Acceptance Criteria  
   
 ```gherkin
Given there is no wishlist that matches the filter criterion
When the user requests to list all wishlists or matching list
Then the request succeeds and returns “no wishlist found"
```

```gherkin
Given there are wishlists in the user’s account that fits the filter criterion
When the user requests to list all or matching wishlists
Then the request succeeds and returns all the matching wishlists
```

**Comment by lingz0108** [comment]
Extracted and splitted from original issue#5: List wishlists

**Comment by ChizhiWang** [comment]
I used date format "%Y-%m-%d" in the implementation.
